name = "djibb"
compatibility_date = "2024-03-20"

d1_databases = [
    { binding = "DJIBB_AUTH", database_name = "djibb-auth", database_id = "f839093e-e2d9-4861-8a3f-05dca1d1a749" },
]

[durable_objects]
bindings = [
  { name = "DJIBB_LIST", class_name = "DjibbList", script_name = "workers" },
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["DjibbList"]