import { WriteTransaction } from 'replicache';
import { z } from 'zod';

export const MutationSchema = z.object({
    clientID: z.string(),
    id: z.number(),
    name: z.string(),
    args: z.any(),
});

/**
 * Request body for a Replicache Pull Request.
 */
export const ReplicachePullRequestSchema = z.object({
    pullVersion: z.literal(1),
    profileID: z.string(),
    clientGroupID: z.string(),
    cookie: z.union([z.number(), z.null()]),
    schemaVersion: z.string(),
});

export type ReplicachePullRequest = z.TypeOf<
    typeof ReplicachePullRequestSchema
>;

export const PushRequestSchema = z.object({
    profileID: z.string(),
    clientGroupID: z.string(),
    mutations: z.array(MutationSchema),
});

export const ReplicacheClientSchema = z.object({
    id: z.string(),
    lastMutationId: z.number(),
    lastModifiedVersion: z.number(),
});

// ReplicacheClient represents an instance of the Replicache JS class
// that has synced with the server.
export type ReplicacheClient = {
    // Globally unique ID, generated by Replicache.
    id: string;

    // Last mutation the server has processed from this client.
    lastMutationID: number;

    // The Version of the top-level List that this Client had a hand
    // in updating. We use this value when responding to a Pull Request
    // because it allows us to know whether this Client has been synced
    // with the frontend.
    lastModifiedVersion: number;
};

export const ReplicacheClientGroupSchema = z.object({
    // The Account ID that created this ReplicacheClientGroup.
    // Optional, but required if the application is authenticated.
    accountId: z.string().nullable(),
    clients: z.array(ReplicacheClientSchema),
    // Globally unique ID, generated by Replicache.
    id: z.string(),
});

export type ReplicacheClientGroup = z.infer<typeof ReplicacheClientGroupSchema>;

// Pick the methods and properties from Replicache's `WriteTransaction`
// so client/server mutators can share a narrower transaction type.
// Excludes `scan` because we don't implement it.
export type SimpleWriteTransaction = Pick<
    WriteTransaction,
    'reason' | 'set' | 'del' | 'location' | 'get' | 'isEmpty'
>;
